#hydra-curriculum-serviceBAM
spring:
  application:
    name: hydra-curriculum-service
  datasource:
    url: jdbc:h2:file:~/test
    username: roll
    password: tide
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2

server:
  port: 8991
#server.context-path=/api/v2/curriculum

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
#eureka.client.serviceUrl.defaultZone=${EUREKA_URI:http://18.219.59.193:8761/eureka}


endpoints:
  actuator:
    enabled: true
    sensitive: false
  sensitive: false
